# Generated by Django 4.0.4 on 2022-09-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_userprofile'),
        ('web_app', '0003_comment_hidden_post_favourites_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to='user_app.userprofile'),
        ),
    ]
