# Generated by Django 4.0.4 on 2022-06-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_post_number_of_comments_alter_comment_comment_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='created',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='number_of_comments',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
