# Generated by Django 4.0.4 on 2022-09-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_remove_post_dislike_remove_post_like_like_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name=''),
        ),
    ]
