# Generated by Django 4.0.4 on 2022-06-30 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_post_favourite_alter_comment_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='created',
        ),
    ]
